/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TosRouteImport } from './routes/tos'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PageToPixelRouteImport } from './routes/page-to-pixel'
import { Route as IncubatorRouteImport } from './routes/incubator'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSealRouteImport } from './routes/admin.seal'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PageToPixelRoute = PageToPixelRouteImport.update({
  id: '/page-to-pixel',
  path: '/page-to-pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubatorRoute = IncubatorRouteImport.update({
  id: '/incubator',
  path: '/incubator',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSealRoute = AdminSealRouteImport.update({
  id: '/admin/seal',
  path: '/admin/seal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/incubator': typeof IncubatorRoute
  '/page-to-pixel': typeof PageToPixelRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/tos': typeof TosRoute
  '/updates': typeof UpdatesRoute
  '/verify': typeof VerifyRoute
  '/admin/seal': typeof AdminSealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/incubator': typeof IncubatorRoute
  '/page-to-pixel': typeof PageToPixelRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/tos': typeof TosRoute
  '/updates': typeof UpdatesRoute
  '/verify': typeof VerifyRoute
  '/admin/seal': typeof AdminSealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/incubator': typeof IncubatorRoute
  '/page-to-pixel': typeof PageToPixelRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/tos': typeof TosRoute
  '/updates': typeof UpdatesRoute
  '/verify': typeof VerifyRoute
  '/admin/seal': typeof AdminSealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/incubator'
    | '/page-to-pixel'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/tos'
    | '/updates'
    | '/verify'
    | '/admin/seal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/incubator'
    | '/page-to-pixel'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/tos'
    | '/updates'
    | '/verify'
    | '/admin/seal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/incubator'
    | '/page-to-pixel'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/tos'
    | '/updates'
    | '/verify'
    | '/admin/seal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  IncubatorRoute: typeof IncubatorRoute
  PageToPixelRoute: typeof PageToPixelRoute
  PortfolioRoute: typeof PortfolioRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  TosRoute: typeof TosRoute
  UpdatesRoute: typeof UpdatesRoute
  VerifyRoute: typeof VerifyRoute
  AdminSealRoute: typeof AdminSealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-to-pixel': {
      id: '/page-to-pixel'
      path: '/page-to-pixel'
      fullPath: '/page-to-pixel'
      preLoaderRoute: typeof PageToPixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubator': {
      id: '/incubator'
      path: '/incubator'
      fullPath: '/incubator'
      preLoaderRoute: typeof IncubatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seal': {
      id: '/admin/seal'
      path: '/admin/seal'
      fullPath: '/admin/seal'
      preLoaderRoute: typeof AdminSealRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  IncubatorRoute: IncubatorRoute,
  PageToPixelRoute: PageToPixelRoute,
  PortfolioRoute: PortfolioRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  TosRoute: TosRoute,
  UpdatesRoute: UpdatesRoute,
  VerifyRoute: VerifyRoute,
  AdminSealRoute: AdminSealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
